services:
  pgdatabase1:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./store1_data:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432

  flaskapp:
    volumes:
    - ".:/app"
    build: .
    ports:
      - 5000:5000
    depends_on:
      - pgdatabase1
